name: github-actions-kata
on:
  push:

jobs:
  print-basic-information:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -al
      - run: echo 'Branch: ${{github.ref_name}}'
      # - run: echo "Commit ref: ${{github.sha}}"
